url: https://erikeng.se
title: "Erik Eng utvecklar för webb &amp; mobilt"
description: "Öppen källkod och tillgänglig data gör dagen intressant och webben bättre."
language: sv-se

author: "Erik Eng"
email: erik@eng.se
dribbble: ptz0n
instagram: ptz0n
twitter: ptz0n
flattr:
    user: ptz0n
    language: sv_SE
facebook:
    app: "481444638550896"
    posts: 5
    width: 500
    admins: "516158352"
analytics:
    profile: "33567818"

permalink: /post/:title.html
markdown: kramdown
timezone: "Europe/Paris"

paginate: 10
paginate_path: "/page-:num/"

sass:
    style: compact

future: false

exclude:
    - "404.html"

plugins:
    - "jekyll-sitemap"
    - "jekyll-redirect-from"
    - "jekyll-paginate"
